### ISSUE TITLE
Duplicate: Unable to ignore clone block or/and its attributes with lifecycle meta-argument options

### ISSUE THREAD

**Issue by johnypony3** [hashicorp/terraform-provider-vsphere#1663]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.1.9

### Terraform Provider

v2.1.1

### Description

I am having this exact issue: #1478

```terraform
lifecycle {
    ignore_changes = [
      clone[0],
    ]
  }
```

results in this:
```terraform
~ clone {
  - linked_clone    = false -> null
  - ovf_network_map = {} -> null
  - ovf_storage_map = {} -> null
  ~ template_uuid   = "423064ae-099a-efd0-0248-79229e597457" -> "4230973e-a3cd-49ad-428a-e1d910087cb5" # forces replacement
  # (1 unchanged attribute hidden)
}
```

### Affected Resources

resource/virtualmachine

### Expected Behavior

the clone is ignored. as per lifecycle rules

### Actual Behavior

clone is not ignored

**Comment by tenthirtyam** [comment]
Does it work with the specific attribute?

```hcl
lifecycle {
    ignore_changes = [
      clone[0].template_uuid,
    ]
  }
```

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by johnypony3** [comment]
It does not. Same behavior.

**Comment by johnypony3** [comment]
Issue has been resolved and has been found to be a user issue.
Thank you (and your customer support team) for all your help.

Root cause: 
* Deployment repo clones the internal module that uses this provider to deploy infra
* The repo above contains a main.tf file that is used to initialize the module
* Said main.tf has a `source` directive coded to be a _git repo_ instead of _local path_
* While the changes were being cloned properly, the `terraform init` command was overriding what was cloned originally
* Debugging is hard, when the change you're testing is not getting executed :D :fliptable:

Fix:
* Updated the main.tf to use a local path in the source directive instead of a git url
