### ISSUE TITLE
Module issues with `main` branch for v2.2.0 milestone

### ISSUE THREAD

**Issue by bobot4258** [hashicorp/terraform-provider-vsphere#1667]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [x] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [x] Do not leave "+1" or other comments that do not add relevant information or questions.
- [x] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.2.2

### Terraform Provider

`main` for v2.2.0 milestone

### VMware vSphere

7.0.3

### Description

I originally ran into an issue when trying to provision VMs with Terraform that was caused by having a vGPU in the template which I found had already been reported https://github.com/hashicorp/terraform-provider-vsphere/issues/1265 and the code to fix it had been added to mainline but not officially released as it is waiting for version 2.2 release.

After compiling a custom vsphere provider using the mainline code and using this with Terraform I was now able to provision VMs with a vGPU attached to them.

I then changed my Terraform file to use Modules and after doing that the vSphere provider now gives me this error.

```console
│ Error: Missing required argument
│
│ The argument "password" is required, but was not set.
╵
╷
│ Error: Missing required argument
│
│ The argument "user" is required, but was not set.

```
This issue is with the currently compiled main branch provider and not my changes going to modules.  I can confirm this because if while using modules in my main.tf file I go back to using the latest 2.1.1 officially released vSphere provider the above error goes away but then I run into my original vGPU issue.  I can also see successful login when running the terraform plan on my vCenter server.

I understand that I am using a none official release but wanted to point this issue out to see if there is any fix for what I am experiencing

### Affected Resources

`vsphere_virtual_machine`

### Terraform Configuration
MAIN FILE

```hcl
provider "vsphere" {
  vsphere_server = var.vsphere_server
  user           = var.vsphere_user
  password       = var.vsphere_password

  allow_unverified_ssl = true
}

module "projects" {
  source = "./modules/mod-win10"
  for_each = var.projects
  instance_count = each.value.instance_count
  host_name_prefix = each.value.host_name_prefix
  
}
```

MODULE FILE

```hcl
data "vault_generic_secret" "setup_credentials" {
  path = "kv/packer"
}

data "vsphere_datacenter" "dc" {
  name = var.datacenter
}

data "vsphere_compute_cluster" "cluster" {
  name          = var.cluster
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_datastore" "datastore" {
  name          = var.datastore_cluster
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name          = var.network_name
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "template" {
  name          = "/${var.datacenter}/vm/Templates/${var.template_name}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "vm" {
  count            = var.instance_count
  name             = "${var.host_name_prefix}-${count.index + 1}"
  folder           = "Test"
  resource_pool_id = "${data.vsphere_compute_cluster.cluster.resource_pool_id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"
  num_cpus = 4
  memory   = 16384
  num_cores_per_socket = 2
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"
  memory_reservation = 16384
  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"
  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    label            = "disk0"
    size             = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
  }

  disk {
    label            = "disk1"
    size             = "${data.vsphere_virtual_machine.template.disks.1.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.1.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.1.thin_provisioned}"
    unit_number      = 1
  }
  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"
    customize {
      windows_options {
        computer_name         = "${var.host_name_prefix}-${count.index + 1}"
        join_domain           = "test.local"
        domain_admin_user     = var.username
        domain_admin_password = "password"
        product_key           = "key"
      }
      network_interface {}
    }
  }
}

resource "null_resource" "provisioner" {
  count = 1
  triggers = {
    master_id = "${element(vsphere_virtual_machine.vm.*.id, count.index)}"
  }
  connection {
    type     = "winrm"
    user     = var.username
    password = "password"
    host     = "${element(vsphere_virtual_machine.vm.*.default_ip_address, count.index)}"
  }
}
```

### Expected Behavior

I should be able to deploy VMs with Terraform like normal

### Actual Behavior

Provider thinks I have not supplied a User and Password for vSphere

```console
Error: Missing required argument
│
│ The argument "password" is required, but was not set.
╵
╷
│ Error: Missing required argument
│
│ The argument "user" is required, but was not set.
```

**Comment by tenthirtyam** [comment]
Please attach a redacted version of your module for issue reproduction along with any debug output.

Thanks!

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
No issues seen in https://github.com/hashicorp/terraform-provider-vsphere/pull/1627/files so we'd need to review other commits to determine impact.

cc @appilon 

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by bobot4258** [comment]
Edited my original post to include the module config

**Comment by tenthirtyam** [comment]
Can you include a redacted version of the module?

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by bobot4258** [comment]
I have added the module config file in as well

**Comment by appilon** [comment]
Hi @bobot4258, after a quick glance, I can't think of any reason why provider configuration (which is when things like credentials is dealt with) has changed at all since last release. Unfortunately at this time I'm going to lean towards having us release 2.2.0, and then seeing if the issue persists, can you verify that you are actually using a local build of the provider with
```
terraform version
```

**Comment by bobot4258** [comment]
Hey @appilon yep I am using the local 2.2 provider
Terraform v1.2.2
on windows_amd64
+ provider local/hashicorp/vsphere v2.2.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/vault v3.6.0
+ provider registry.terraform.io/hashicorp/vsphere v2.1.1

I don't run into this odd credential issue when I was just using the 2.1.1 it only happens after I switch to using 2.2.0 and using modules specifically. I also see this exact issue when testing on two different computers.

Do you have any sort of ETA on when 2.2.0 will be officially released?

**Comment by appilon** [comment]
I can't give any exact timelines but I am making it a priority, out of curiosity, can you roll back Terraform to version 1.0.11 let's say (just to see if it's a Core issue)

**Comment by bobot4258** [comment]
I had originally ran into this issue when using Terraform 1.1.9 so upgraded to 1.2.2, I just tried using 1.0.11 and I get the same issue.

**Comment by appilon** [comment]
Okay, last ditch request, can you check the codebase out to `v2.1.1` and make a local build and run against a local `v2.1.1`. I'd like to see if it's something to do with local builds maybe?

**Comment by bobot4258** [comment]
Thank you for making the v2.2 release a priority. Tested with that and my issue in this ticket is resolved and I am apply to successfully deploy stuff.

**Comment by tenthirtyam** [comment]
Thanks for the update, @bobot4258 - much appreciated. I'll close this issue.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
